name: Deploy React App

on:
  push:
    branches:
      - main  # Change this if your default branch is different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Use the version you need

    - name: Install dependencies
      run: npm install

    - name: Build the app
      run: npm run build

    - name: Deploy to Truehost
      uses: appleboy/scp-action@master
      with:
        host: 102.212.247.162  # Your Truehost server IP
        username: pxvxkmkb Your Truehost username
        password: Krd364ca@2004  # Your Truehost password
        source: "build/*"
        target: /home/pxvxkmkb/public_html# Path to your public_html folder